sudo: required
services:
- docker
matrix:
  include:
  # - language: php
  #   php:
  #   - 7.2
  #   cache:
  #     directories:
  #     - vendor
  #     - "$HOME/.composer/cache"
  #   install:
  #   - rm composer.lock
  #   - composer update --no-scripts
  #   - cp .env.testing .env
  #   - php artisan clear-compiled
  #   - php artisan env
  #   - wget -q https://github.com/firefly-iii/test-data/raw/master/storage/database.sqlite
  #     -O storage/database/database.sqlite
  #   - mkdir -p build/logs
  #   script:
  #   - "./vendor/bin/phpunit -c phpunit.coverage.xml"
  #   after_success:
  #   - travis_retry php vendor/bin/php-coveralls -x storage/build/clover-all.xml
  #   branches:
  #     only:
  #     - develop
  #     - master
  - language: bash
    script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build -f Dockerfile.rpi -t odyno/rpi-firefly-iii .
    - |
      if [ "$TRAVIS_BRANCH" == "rpi-docker" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        #docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        #TAG=$(grep "ENV FIREFLY_III_VERSION" Dockerfile | awk 'NF>1{print $NF}')
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        TAG=$FIREFLY_III_VERSION
        docker tag odyno/rpi-firefly-iii odyno/rpi-firefly-iii:$TAG
        docker push odyno/rpi-firefly-iii:$TAG
        docker push odyno/rpi-firefly-iii
      fi
    branches:
      only:
      - rpi-docker
env:
  global:
  - FIREFLY_III_VERSION: 0.0.1
  - DOCKER_USER: odyno
  - secure: q5qMh3FiW+EK5p0aSlfAeI/IQ19417/HgLmU+CudtJGXPUnUA5djrXey6/p/wXzh1iTIsLe6fIQ3hDkuaIfYKHjTGmPDk+Fu22MjJLjpjdb6ZP0ir3YM54+OVRf3+0MbfbzUUX95AQGOX5c2XqBSVI1DND3eiZkZumelgbTntNBYapZWQeHIE1zQE9+ujsu6wucQ7+IzKzpwDQJB/QmoEYaJnTnnd3Wr6V2eyFqmv87dcb+Q2Et8zWddYpomHOihWIA+KEh6E91hCm/PsqVEb/DgFeYxAhD80mYj6giSV6y5V5jm7mylNhCzP612yCCurJU6PGMo52yI0he50z/Z+O4UR0Q17Rdo/Yv5Z31uUdtuDml28Zn7LR/7ybK7ca5QMZl3H6w361A93zUzKZxUDOUreX8RGAfg0nmIz3Q1npYnb7LhSFong9mpWvrsLkbXqFxZPE0os71mIis9rrqHBvYLNYDX5V3NotuG1cYvOU+4QTxwsXRYaZtNmqW48iV5+Fe9zhXllLQFJ5f/BjoPHEfQXg2QTCRPLY076476F7HTNdiOSVsiAZV04WNHl91dvxsh2tFIgKcEcpO51wODgKBI0PnoM7r03egqcVhi6IvZWTWF+iSPqny4HQ5bh4uzh8Q3hgnwpgi1qp4StJ+KfALC7Zx1ivt9kS5x2A6eYes=
