sudo: required
services:
- docker
matrix:
  include:
  - language: php
    php:
    - 7.2
    cache:
      directories:
      - vendor
      - "$HOME/.composer/cache"
    install:
    - rm composer.lock
    - composer update --no-scripts
    - cp .env.testing .env
    - php artisan clear-compiled
    - php artisan env
    - wget -q https://github.com/firefly-iii/test-data/raw/master/storage/database.sqlite
      -O storage/database/database.sqlite
    - mkdir -p build/logs
    script:
    - "./vendor/bin/phpunit -c phpunit.coverage.xml"
    after_success:
    - travis_retry php vendor/bin/php-coveralls -x storage/build/clover-all.xml
    branches:
      only:
      - develop
      - master
  - language: bash
    script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build -t odyno/rpi-firefly-iii .
    - |
      if [ "$TRAVIS_BRANCH" == "rpi-docker" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        #docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        #TAG=$(grep "ENV FIREFLY_III_VERSION" Dockerfile | awk 'NF>1{print $NF}')
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        TAG=$FIREFLY_III_VERSION
        docker tag odyno/rpi-firefly-iii odyno/rpi-firefly-iii:$TAG
        docker push odyno/rpi-firefly-iii:$TAG
        docker push odyno/rpi-firefly-iii
      fi
    branches:
      only:
      - rpi-docker
env:
  global:
  - FIREFLY_III_VERSION: 0.0.1
  - DOCKER_USER: odyno
  - secure: J9xgh2sMlhMYr/CY24Tr2cAiRqbY5ktR1yueMTiH/CNtNuWN2x1cORd4lZuXMMwfeC24VkhOEbp/6qufao0OZaUZiQFrPa9uVSTxsQBbZI42CvlXmnnTeUG6UsllD7JDR9omtL+evffsi7FGSkQMJRpg5zSfCeBA11GD1lu9pXUSjwLULCrXevLIAKqBJ9UXU2fhdqevNogLupUuPgDgPLzv9dXqQNbCCicnu/6seTVCJbshHlISi6jU42NiyKONmDKCSYAeCM/G8pa3Rl66L970IgH4dVOaoJRkbG3mF6Cfj73CobX+ThKkcbiFgMpP6/zcHmSuyauFXmv3xInXrInnOkGA/doDdpyhehVxUPOPHcPN7RWv14Mufo26gI455XZc0x/iIWCc6dEAi79Pz/EuhXjXtSr3UHdfObgRR/MhjX0Q8vZqDv0rpKGPqMoblERQysCD03bNcm2g1i+Rh8BiCJYYwTm8H5GGR8ONPaITgPXrZAKmsbAcGWzCjT724gneEVbEGSCKCmP/F+ZQovaWlhuR1W7IlsPSsOht4on1/CkzrNstt0C/UfP1RI13U9isDVdhAijLC69vWBfjv+2mEiQ/HsWieE+X8DzlqxQfnSTCo+oWsSkf4bbC5nSrlomM4XbLTypaSqoOjXqTWUXEDhJslOcflmOJA0iBivU=
